(() => {
  const passive = (type, value) => ({ type, value, trigger: 'passive' });
  const proc = (type, value, chance, trigger, duration = null) => ({ type, value, chance, trigger, duration });
  const legacy = 'https://nfdmo.wiki.gg/wiki/Deck_System';
  const official = (idx) => `https://ptladmo.gameking.com/News/EventView.aspx?idx=${idx}`;
  const d = (id, name, digimons, effects, extra = {}) => ({ id, name, digimons, effects, ...extra });

  window.DECK_BUFF_DATA = {
    revisedAt: '29/09/2026',
    effectLabels: {
      attackSpeed: 'Velocidade de Ataque', skillDamage: 'Dano de Skill', normalDamage: 'Dano de Ataque Básico',
      critDamage: 'Dano Crítico', hp: 'HP', attributeDamage: 'Dano de Atributo', finalDamage: 'Dano Final',
      attackAmp: 'Amplificação de Ataque', attack: 'Ataque', hit: 'Precisão', cooldownReset: 'Reset de recarga'
    },
    decks: [
      d('four-holy-beasts', 'Quatro Bestas Sagradas', ['Azulongmon', 'Baihumon', 'Ebonwumon', 'Zhuqiaomon'], [passive('critDamage', 30)], {source: legacy, sourceType: 'community'}),
      d('fusion-higher', 'Fusão para Evoluir ao Superior', ['Alphamon Ouryuken', 'Omegamon', 'Shakkoumon (Jogress)'], [proc('cooldownReset', 100, 9, 'normalHit')], {source: legacy, sourceType: 'community', note: 'Composição exigida na versão global; formas opcionais antigas foram removidas da rota.'}),
      d('three-archangels', 'Três Arcanjos', ['Seraphimon (linha Pegasusmon)', 'Ophanimon (linha Mastemon)', 'Cherubimon (Branco)'], [proc('normalDamage', 15, 3, 'normalHit', 5)], {source: legacy, sourceType: 'community'}),
      d('adventure-main', 'Protagonistas da Aventura', ['Agumon (Clássico)', 'Piyomon', 'Gabumon (linha MetalGarurumon)', 'Gomamon (linha Ikkakumon)', 'Patamon (linha Pegasusmon)', 'Palmon (linha Togemon)', 'Gatomon (linha Nefertimon)', 'Tentomon'], [passive('attackSpeed', 8)], {source: legacy, sourceType: 'community'}),
      d('burst-ultimate-wings', 'Asas Supremas Explosivas', ['Gallantmon Modo Carmesim', 'Imperialdramon Modo Paladino', 'Lucemon Modo Satã', 'MaloMyotismon', 'Ornismon', 'TyrantKabuterimon', 'Valdurmon (não Jogress)', 'VictoryGreymon'], [passive('attackSpeed', 15)], {source: legacy, sourceType: 'community'}),
      d('burst-ultimate-wings-ii', 'Asas Supremas Explosivas II', ['Boltboutamon', 'Mastemon', 'Lucemon Modo Satã', 'Megidramon', 'Dynasmon X', 'Duftmon X', 'UlforceVeedramon X', 'Dexmon X', 'GrandisKuwagamon X', 'Valkyrimon'], [passive('attackSpeed', 15), proc('normalDamage', 15, 15, 'skillUse', 10)], {source: legacy, sourceType: 'community'}),
      d('seafood-stew', 'Ensopado de Frutos do Mar', ['Gesomon', 'Mushroomon', 'Pumpkinmon', 'Syakomon'], [passive('hp', 10)], {source: legacy, sourceType: 'community'}),
      d('sharp-blue-sword', 'Onda Afiada de Espada Azul', ['Grademon', 'Knightmon', 'Minervamon', 'OuRyumon', 'Zanbamon'], [proc('normalDamage', 10, 6, 'normalHit', 10)], {source: legacy, sourceType: 'community'}),
      d('instant-red-gun', 'Disparo Instantâneo da Arma Vermelha', ['Astamon', 'Chaosdramon', 'Deputymon', 'Gargomon', "Z'dGarurumon"], [proc('skillDamage', 8, 7, 'skillUse', 12)], {source: legacy, sourceType: 'community'}),
      d('so-cute', 'Tão Fofos', ['Doggymon', 'Kudamon', 'Salamon (linha Nefertimon)', 'Terriermon'], [passive('critDamage', 15)], {source: legacy, sourceType: 'community'}),
      d('four-dark-masters', 'Quatro Mestres das Trevas', ['Machinedramon', 'MetalSeadramon', 'Piedmon', 'Puppetmon'], [proc('skillDamage', 12, 5, 'skillUse', 10)], {source: legacy, sourceType: 'community'}),
      d('ego-darkness', 'Ego da Escuridão', ['Apocalymon (linha MechaNorimon)', 'Apocalymon (linha Betamon)', 'Apocalymon (linha Soulmon)', 'Apocalymon (linha Woodmon)'], [passive('hp', 15), proc('normalDamage', 12, 70, 'normalHit', 5)], {source: legacy, sourceType: 'community'}),
      d('hyper-spirit', 'Hiper Evolução Espírito', ['KaiserGreymon', 'MagnaGarurumon'], [passive('hp', 10), passive('critDamage', 2), proc('normalDamage', 15, 50, 'normalHit', 5)], {source: legacy, sourceType: 'community'}),
      d('ancient-spirit', 'Evolução Espírito Ancestral', ['KaiserGreymon', 'MagnaGarurumon', 'Susanoomon'], [passive('hp', 15), passive('critDamage', 5), proc('normalDamage', 25, 40, 'normalHit', 5)], {source: legacy, sourceType: 'community'}),
      d('legendary-vaccine-knights', 'Cavaleiros Lendários de Vacina', ['Magnamon', 'Omegamon Zwart', 'Imperialdramon Modo Paladino (Jogress)', 'Susanoomon', 'Alphamon Ouryuken X', 'Omegamon X'], [passive('attackSpeed', 15), passive('hp', 15), proc('normalDamage', 20, 30, 'normalHit', 7)], {source: legacy, sourceType: 'community'}),
      d('omega', 'OMEGA', ['Omegamon Zwart', 'Omegamon Alter-S', 'Omegamon'], [passive('skillDamage', 12)], {source: legacy, sourceType: 'community'}),
      d('mega-omega', 'MEGA-OMEGA', ['Omegamon Zwart', 'Omegamon Alter-S', 'Omegamon', 'Omegamon Zwart D', 'Omegamon Alter-B'], [passive('skillDamage', 15), passive('attackSpeed', 15), proc('critDamage', 100, 3, 'normalHit', 10)], {source: legacy, sourceType: 'community'}),
      d('royal-knights-x', 'Cavaleiros Reais X', ['Omegamon X', 'Alphamon Ouryuken [Despertado]', 'Examon X', 'Gallantmon X', 'UlforceVeedramon X', 'Magnamon X', 'Dynasmon X', 'LordKnightmon X', 'Sleipmon X', 'Craniamon X', 'Duftmon X', 'Gankoomon X', 'Jesmon X'], [passive('hp', 20), passive('attackSpeed', 17), proc('critDamage', 100, 5, 'normalHit', 10)], {source: legacy, sourceType: 'community'}),

      d('legendary-ancient-warrior', 'Manifeste-se! Guerreiro Lendário Antigo', ['Imperialdramon Modo Paladino [Despertado]', 'Omegamon'], [passive('attackSpeed', 17), passive('hit', 10), passive('critDamage', 130)], {source: official(160), sourceType: 'official', date: '22/05/2025'}),
      d('stop-diablomon', 'Detenha o Diablomon!', ['Imperialdramon Modo Paladino [Despertado]', 'Armagemon [Fusão]', 'Diablomon'], [passive('attackSpeed', 18), passive('attributeDamage', 5), passive('normalDamage', 30)], {source: official(160), sourceType: 'official', date: '22/05/2025'}),
      d('dark-justice', 'Justiça Sombria', ['Kuzuhamon Modo Miko', 'Eosmon (Mega)', 'BloomLordmon', 'ZeedMillenniumon [Despertado]'], [passive('attackSpeed', 22), passive('attributeDamage', 5), passive('critDamage', 100), passive('attackAmp', 15)], {source: official(160), sourceType: 'official', date: '22/05/2025'}),
      d('peaceful-savior', 'Salvador Pacificador', ['Omegamon Modo Misericordioso', 'Shoutmon X7 Modo Superior', 'Gallantmon Modo Carmesim [Despertado]', 'Imperialdramon Modo Paladino [Despertado]'], [passive('attackSpeed', 22), passive('hp', 5), passive('skillDamage', 100), passive('attackAmp', 15)], {source: official(160), sourceType: 'official', date: '22/05/2025'}),
      d('corrupted-purification', 'O Ritual de Purificação Corrompido', ['Kuzuhamon Modo Miko', 'Kuzuhamon', 'Siriusmon'], [passive('attackSpeed', 18), passive('hp', 40), passive('attributeDamage', 5)], {source: official(160), sourceType: 'official', date: '22/05/2025'}),
      d('digital-world-guardian', 'Guardião do Mundo Digital', ['Omegamon Modo Misericordioso', 'Shoutmon X7 Modo Superior', 'Kuzuhamon Modo Miko', 'Gallantmon Modo Carmesim [Despertado]'], [passive('attackSpeed', 22), passive('hp', 40), passive('skillDamage', 70), passive('critDamage', 150)], {source: official(160), sourceType: 'official', date: '22/05/2025'}),
      d('reunion', 'Reencontro', ['Alphamon Ouryuken [Supremacia]', 'Omegamon'], [passive('attackSpeed', 20), proc('attackSpeed', 10, 20, 'normalHit'), passive('hit', 7)], {source: official(163), sourceType: 'official', date: '12/06/2025', note: 'A nota oficial não informa a duração do efeito ativado.'}),
      d('real-world-invasion', 'Invasão ao Mundo Real!', ['Lucemon Modo Satã [Supremacia]', 'Agnimon', 'Fairimon', 'Chakkumon', 'Arbormon', 'Grotmon', 'Wolfmon', 'Blitzmon', 'Lanamon', 'Lowemon', 'Mercuremon'], [passive('attackSpeed', 18), passive('attributeDamage', 7), passive('hit', 10)], {source: official(168), sourceType: 'official', date: '24/07/2025'}),
      d('last-evolution-bonds', 'Última Evolução: Laços', ['Agumon - Laços de Coragem', 'Omegamon', 'Eosmon (Mega)'], [passive('attackSpeed', 18), passive('skillDamage', 130), passive('attack', 45)], {source: official(172), sourceType: 'official', date: '21/08/2025'}),
      d('our-hope-light', 'Nossa Esperança, Nossa Luz', ['Goddramon', 'Holydramon', 'Millenniumon', 'WarGreymon [Despertado]', 'MetalGarurumon [Despertado]', 'ZeedMillenniumon [Despertado]'], [passive('attackSpeed', 19), passive('hp', 45), passive('skillDamage', 200)], {source: official(178), sourceType: 'official', date: '02/10/2025'}),
      d('enchantment-justice-wings', 'Asas do Encantamento e Asas da Justiça', ['Lilithmon [Despertado/Resistência]', 'Alphamon Ouryuken [Supremacia]'], [passive('attackSpeed', 20), passive('hp', 30), passive('attributeDamage', 7)], {source: official(184), sourceType: 'official', date: '13/11/2025'}),
      d('abyss-terror-abbadomon', 'Terror do Abismo', ['Abbadomon', 'WarGreymon [Despertado]', 'MetalGarurumon [Despertado]', 'Seraphimon', 'Ophanimon', 'Rosemon', 'HerculesKabuterimon', 'Vikemon', 'Phoenixmon'], [passive('attackSpeed', 18), passive('skillDamage', 85), proc('skillDamage', 75, 20, 'normalHit')], {variant: 'Abbadomon', source: official(195), sourceType: 'official', date: '29/01/2026', note: 'A nota oficial não informa a duração do efeito ativado.'}),
      d('abyss-terror-core', 'Terror do Abismo', ['Abbadomon', 'Abbadomon Core'], [passive('attackSpeed', 18), passive('skillDamage', 180), passive('critDamage', 180)], {variant: 'Abbadomon Core', source: official(201), sourceType: 'official', date: '12/03/2026'}),
      d('complete-and-unknown-data', 'Dados Completos e Dados de Origem Desconhecida', ['Abbadomon', 'Abbadomon Core', 'Eosmon (Mega)', 'Agumon - Laços de Coragem', 'Kuzuhamon Modo Miko', 'Shoutmon X7 Modo Superior'], [passive('attackSpeed', 25), passive('attributeDamage', 12), passive('finalDamage', 25), passive('hp', 45)], {source: official(201), sourceType: 'official', date: '12/03/2026'}),
      d('wings-protect-justice', 'Asas que Protegem a Justiça', ['Omegamon X [Supremacia]', 'Alphamon Ouryuken [Despertado]'], [passive('attackSpeed', 18), passive('attributeDamage', 4), passive('attackAmp', 15)], {source: official(204), sourceType: 'official', date: '02/04/2026'}),
      d('wings-seduce-justice', 'Bater de Asas que Seduz a Justiça', ['Omegamon X [Supremacia]', 'Lilithmon [Despertado/Resistência]'], [passive('attackSpeed', 20), passive('skillDamage', 150), passive('attributeDamage', 3)], {source: official(204), sourceType: 'official', date: '02/04/2026'}),
      d('neutralizers', 'Aqueles que Neutralizam', ['Omegamon X [Supremacia]', 'Lucemon Modo Satã [Supremacia]', 'Alphamon Ouryuken [Supremacia]', 'ZeedMillenniumon [Despertado]', 'Holydramon'], [passive('attackSpeed', 25), passive('hit', 20), passive('attributeDamage', 10), passive('skillDamage', 140)], {source: official(204), sourceType: 'official', date: '02/04/2026'}),
      d('larc-sovereign', 'O Soberano de Larc', ['Quantumon'], [passive('attackSpeed', 18), passive('skillDamage', 180), passive('critDamage', 200)], {source: official(214), sourceType: 'official', date: '11/06/2026'}),
      d('sends-digimon-human-world', 'O Ser que Envia Digimons ao Mundo Humano', ['Quantumon', 'BloomLordmon'], [passive('attackSpeed', 19), passive('hp', 45), passive('skillDamage', 200)], {source: official(214), sourceType: 'official', date: '11/06/2026'}),
      d('neutral-nature-digimon', 'Digimon de Natureza Neutra', ['Quantumon', 'Kuzuhamon Modo Miko', 'Shoutmon X7 Modo Superior'], [passive('attackSpeed', 20), passive('attributeDamage', 5), passive('critDamage', 100), passive('attackAmp', 15)], {source: official(214), sourceType: 'official', date: '11/06/2026'}),
      d('descended-brilliance', 'Aquele que Desceu com o Brilho', ['Apollomon'], [passive('attackSpeed', 16), passive('skillDamage', 165), passive('critDamage', 200), passive('hp', 20)], {source: official(222), sourceType: 'official', date: '30/07/2026'}),
      d('brilliance-faces-despair', 'O Brilho que Enfrenta o Desespero', ['Apollomon', 'Omegamon Modo Misericordioso', 'Susanoomon [Supremacia]', 'Abbadomon', 'Abbadomon Core', 'Lucemon Modo Satã [Supremacia]', 'DarknessBagramon'], [passive('attackSpeed', 25), passive('attributeDamage', 12), passive('finalDamage', 25), passive('skillDamage', 100)], {source: official(222), sourceType: 'official', date: '30/07/2026'}),
      d('sun-lament-whispered', 'Lamento do Sol, Whispered', ['Apollomon Whispered'], [passive('attackSpeed', 16), passive('skillDamage', 165), passive('critDamage', 200), passive('hp', 20)], {source: official(231), sourceType: 'official', date: '17/09/2026'}),
      d('hidden-side-inverted-sun', 'O Lado Oculto do Sol Invertido', ['Apollomon Whispered', 'Apollomon'], [passive('attackSpeed', 20), passive('skillDamage', 180), passive('critDamage', 150), passive('hit', 12)], {source: official(231), sourceType: 'official', date: '17/09/2026'}),
      d('eternal-destruction-chaos', 'Destruição e Caos Eternos', ['Apollomon Whispered', 'Lucemon Modo Satã [Supremacia]', 'ZeedMillenniumon [Despertado]', 'Abbadomon', 'Abbadomon Core'], [passive('attackSpeed', 25), passive('skillDamage', 170), passive('attributeDamage', 8), passive('hp', 35)], {source: official(231), sourceType: 'official', date: '17/09/2026'})
    ]
  };
})();
